# Generated by Django 6.1 on 2026-08-20 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battery', '0001_initial'),
        ('customers', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scooter_id', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=30)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('chassis_number', models.CharField(max_length=100, unique=True)),
                ('motor_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('SOLD', 'Sold'), ('SERVICE', 'In Service'), ('INACTIVE', 'Inactive')], default='IN_STOCK', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scooters', to='customers.customer')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scooters', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ScooterBatteryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_on', models.DateField()),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for replacement, if applicable', max_length=255)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scooter_history', to='battery.battery')),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_history', to='scooters.scooter')),
            ],
            options={
                'verbose_name_plural': 'Scooter battery histories',
                'ordering': ['-installed_on'],
            },
        ),
    ]
