# Generated by Django 6.1 on 2026-08-20 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('battery_model', models.CharField(max_length=100)),
                ('battery_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('manufacturing_date', models.DateField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('g_code', models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2')], max_length=2)),
                ('warranty_period_months', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='CREATED', max_length=15)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Battery status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_id', models.CharField(help_text='e.g. Battery 001', max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('battery_type', models.CharField(max_length=100)),
                ('g_code', models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2')], max_length=2)),
                ('manufacturing_date', models.DateField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ADDED', 'Added'), ('IN_STOCK', 'In Stock'), ('ASSIGNED_VENDOR', 'Assigned to Vendor'), ('SOLD', 'Sold'), ('ASSIGNED_CUSTOMER', 'Assigned to Customer'), ('INSTALLED', 'Installed'), ('IN_SERVICE', 'In Service'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('REPLACED', 'Replaced'), ('INACTIVE', 'Inactive')], default='ADDED', max_length=20)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='battery_qr/')),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batteries', to='customers.customer')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
