# Generated by Django 5.2.7 on 2026-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='battery_id',
            field=models.CharField(help_text='e.g. Battery 001', max_length=50),
        ),
    ]
