# Generated by Django 5.2.7 on 2026-09-18 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_custom_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.customrole'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin / CRM Admin'), ('SALES', 'Sales Team'), ('VENDOR', 'Vendor')], default='SALES', max_length=10),
        ),
    ]
