# Generated by Django 5.2.7 on 2026-08-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_sale'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='vendors.vendor'),
        ),
    ]
