# Generated by Django 5.2.7 on 2026-09-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.AddField(
            model_name='product',
            name='public_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Visible to all regular site visitors', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special price visible only to logged-in vendors', max_digits=12, null=True),
        ),
    ]
