# Generated by Django 5.2.7 on 2026-09-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_base_price_product_public_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Write specifications'),
        ),
    ]
